import Head from 'next/head'
import Header from "../components/Header";
import {Container} from "react-bootstrap";
import NewGoodForm from "../components/NewGoodForm";
import React from "react";
import CatalogTable from "../components/CatalogTable";
import {useSelector} from "react-redux";
import Empty from "../components/Empty";

export default function Home() {
    const isEmpty = useSelector(state => state.catalog.length <= 0)
    return (
        <>
            <Head>
                <title>Каталог</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <Container>
                <main>
                    <h1 className="mb-3">Каталог</h1>
                    <NewGoodForm/>
                    <div className="my-5"/>
                    {isEmpty?<Empty/>:<CatalogTable/>}
                </main>
            </Container>
        </>
    )
}
