import Head from 'next/head'
import Header from "../components/Header";
import {Container} from "react-bootstrap";
import NewGoodForm from "../components/NewGoodForm";
import React from "react";
import CatalogTable from "../components/CatalogTable";

export default function Home() {
    return (
        <>
            <Head>
                <title>Каталог</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <Container>
                <main>
                    <NewGoodForm/>
                    <div className="my-5"/>
                    <CatalogTable/>
                </main>
            </Container>
        </>
    )
}
